trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- powershell: 'choco install wixtoolset '

- bash: "curl -o jdk.7z -L $(jdk_win)"

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.7z' 
    destinationFolder: 'jdk'

- bash: './gradlew installDist -Dorg.gradle.java.home=jdk'

- powershell: 'jdk/bin/javapackager -deploy -outdir target -outfile Trinity+ -srcdir build/install/Trinity+/lib -appclass toliner.trinityplus.TrinityPlusApp -name Trinity+ -title Trinity+ -native installer -Bvendor=toliner -BsystemWide=false'
