name: $(BuildID)-$(Date:yyyyMMdd)-$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- bash: "curl -o jdk.7z -L $(jdk_win)"

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.7z' 
    destinationFolder: 'jdk'

- bash: './gradlew installDist -Dorg.gradle.java.home=jdk'

- powershell: 'jdk/bin/javapackager -deploy -outdir target -outfile Trinity+-$(Build.BuildNumber) -srcdir build/install/Trinity+/lib -appclass toliner.trinityplus.TrinityPlusApp -name Trinity+ -title Trinity+ -native installer -Bvendor=toliner -BsystemWide=false'

- task: CopyFiles@2
  inputs:
    contents: 'target\**\*.exe'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    overWrite: true #Optional

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: trinity-win