trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:

- bash: "curl -o jdk.7z -L $(jdk_win)"
  name: 'dlJDK'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.7z' 
    destinationFolder: 'jdk'
  name: 'extractJDK'

- bash: './gradlew installDist -Dorg.gradle.java.home=jdk'
  name: 'build'

- powershell: |
    $env:PATH += (";" + $env:WIX + "bin")
    jdk/bin/javapackager -deploy -outdir target -outfile Trinity+ -srcdir build/install/Trinity+/lib -appclass toliner.trinityplus.app.TrinityPlusApp -name Trinity+ -title Trinity+ -native installer -Bvendor=toliner -BsystemWide=false
  name: 'package'

- task: CopyFiles@2
  inputs:
    contents: 'target\**\?(*.exe|*.msi)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    overWrite: true #Optional

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: trinity-win